stages:
  - test

variables:
  GRID_URL: "http://selenium-hub:4444/wd/hub"
  BROWSER: "chrome"
  EXECUTOR: "remote"
  DEFAULT_TIMEOUT: "10"

services:
  - name: selenium/hub:4.25.0
    alias: selenium-hub
  - name: selenium/node-chrome:4.25.0
    alias: chrome
    command:
      - bash
      - c
      - "SE_NODE_MAX_SESSIONS=4 SE_NODE_OVERRIDE_MAX_SESSIONS=true /opt/bin/entry_point.sh"
  - name: selenium/node-firefox:4.25.0
    alias: firefox
    command:
      - bash
      - c
      - "SE_NODE_MAX_SESSIONS=4 SE_NODE_OVERRIDE_MAX_SESSIONS=true /opt/bin/entry_point.sh"

test:
  stage: test
  image: python:3.11-slim
  before_script:
    - pip install --upgrade pip
    - pip install selenium pytest pytest-xdist allure-pytest
    - pip install -r requirements.txt
  script:
    # Run tests in parallel. Limit workers to 1 for nodes with max 1 session
    - pytest -n 4 --browser_name=$BROWSER --executor=$EXECUTOR --alluredir=allure-results
  artifacts:
    paths:
      - allure-results
    when: always
