stages:
  - test
  - report

variables:
  PYTHONPATH: "$CI_PROJECT_DIR"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  ALLURE_RESULTS_DIR: "allure-results"
  ALLURE_REPORT_DIR: "allure-report"

cache:
  paths:
    - .cache/pip

# ---------- Stage 1: Run Tests ----------
run_tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.45.0-jammy  # has browsers + drivers preinstalled
  script:
    - pip install -r requirements.txt
    - mkdir -p $ALLURE_RESULTS_DIR
    - pytest --dist=loadscope --browser_name=chrome --executor=local --alluredir=$ALLURE_RESULTS_DIR -n 2
  artifacts:
    when: always
    paths:
      - $ALLURE_RESULTS_DIR
    expire_in: 2 days

# ---------- Stage 2: Generate Allure Report ----------
allure_report:
  stage: report
  image: frankescobar/allure-docker-service:latest
  script:
    - allure generate $ALLURE_RESULTS_DIR -o $ALLURE_REPORT_DIR --clean
  artifacts:
    paths:
      - $ALLURE_REPORT_DIR
    expire_in: 5 days
  when: always
